/**
 * Database type definitions.
 *
 * In production, this file is auto-generated by running:
 *   npx supabase gen types typescript --project-id $SUPABASE_PROJECT_ID > src/types/database.ts
 *
 * The types below are a hand-written placeholder that matches the schema
 * defined in our migrations. Replace this file with the generated version
 * once the Supabase project is provisioned.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
        };
        Update: {
          full_name?: string | null;
          avatar_url?: string | null;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: "consultant" | "manager" | "admin" | "viewer";
          created_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          user_id: string;
          role: "consultant" | "manager" | "admin" | "viewer";
          updated_by?: string | null;
        };
        Update: {
          role?: "consultant" | "manager" | "admin" | "viewer";
          updated_by?: string | null;
        };
      };
      customers: {
        Row: {
          id: string;
          external_account_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          external_account_id: string;
          name: string;
          is_active?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          name?: string;
          is_active?: boolean;
          updated_by?: string | null;
        };
      };
      service_lines: {
        Row: {
          id: string;
          name: string;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          display_order?: number;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          display_order?: number;
          is_active?: boolean;
        };
      };
      workstreams: {
        Row: {
          id: string;
          name: string;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          display_order?: number;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          display_order?: number;
          is_active?: boolean;
        };
      };
      activity_types: {
        Row: {
          id: string;
          name: string;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          display_order?: number;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          display_order?: number;
          is_active?: boolean;
        };
      };
      time_entries: {
        Row: {
          id: string;
          user_id: string;
          customer_id: string;
          service_line_id: string;
          workstream_id: string;
          activity_type_id: string;
          entry_date: string;
          duration_minutes: number;
          notes: string;
          created_at: string;
          updated_at: string;
          created_by: string;
          updated_by: string;
        };
        Insert: {
          user_id: string;
          customer_id: string;
          service_line_id: string;
          workstream_id: string;
          activity_type_id: string;
          entry_date: string;
          duration_minutes: number;
          notes?: string;
          created_by: string;
          updated_by: string;
        };
        Update: {
          customer_id?: string;
          service_line_id?: string;
          workstream_id?: string;
          activity_type_id?: string;
          entry_date?: string;
          duration_minutes?: number;
          notes?: string;
          updated_by?: string;
        };
      };
      reporting_periods: {
        Row: {
          id: string;
          customer_id: string;
          period_month: string;
          status: "draft" | "in_review" | "approved";
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          customer_id: string;
          period_month: string;
          status?: "draft" | "in_review" | "approved";
        };
        Update: {
          status?: "draft" | "in_review" | "approved";
        };
      };
      customer_import_logs: {
        Row: {
          id: string;
          uploaded_by: string;
          file_name: string;
          row_count: number;
          inserted_count: number;
          updated_count: number;
          error_count: number;
          errors: Json;
          status: "pending" | "processing" | "completed" | "failed";
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          uploaded_by: string;
          file_name: string;
          row_count: number;
        };
        Update: {
          inserted_count?: number;
          updated_count?: number;
          error_count?: number;
          errors?: Json;
          status?: "pending" | "processing" | "completed" | "failed";
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
    };
    Functions: {
      get_my_role: {
        Args: Record<string, never>;
        Returns: string;
      };
      is_period_locked: {
        Args: { p_customer_id: string; p_entry_date: string };
        Returns: boolean;
      };
      get_monthly_report: {
        Args: {
          p_customer_id: string;
          p_month: string;
          p_weekly?: boolean;
        };
        Returns: {
          service_line_name: string;
          service_line_order: number;
          workstream_name: string;
          workstream_order: number;
          week_start: string | null;
          total_minutes: number;
          total_hours: number;
        }[];
      };
    };
  };
}

/** Shorthand type aliases for common row types. */
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type UserRoleRow = Database["public"]["Tables"]["user_roles"]["Row"];
export type Customer = Database["public"]["Tables"]["customers"]["Row"];
export type ServiceLine = Database["public"]["Tables"]["service_lines"]["Row"];
export type Workstream = Database["public"]["Tables"]["workstreams"]["Row"];
export type ActivityType = Database["public"]["Tables"]["activity_types"]["Row"];
export type TimeEntry = Database["public"]["Tables"]["time_entries"]["Row"];
export type ReportingPeriod = Database["public"]["Tables"]["reporting_periods"]["Row"];
